server:
  port: 8085

cloud:
  eureka-host: localhost

currency:
  client:
    url: "https://www.cbr.ru/scripts/XML_daily.asp"

spring:
  application:
    name: currency

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka
