server:
  port: 8085

currency:
  client:
    url: "https://www.cbr.ru/scripts/XML_daily.asp"

spring:
  application:
    name: currency-rate-service

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
